# B4-1001.xform captures a good transformation for the two off files
# made by B4-1001.scm.  Either alone or both together make interesting
# images at that transform.

# That same transormation is (accidentally) also pretty good for the
# two off files made by B4-1155-5511.scm, which also make good pics
# alone or together.

# B4-1001-2.gcl and B4-1001-3.gcl are just different angles on the same
# thing.  Which one to show?  Maybe both in different colors?
